#pragma once

/* ═══════════════════════════════════════════════════════════════════════════
 * app_config.h — Central configuration for EdgeVision
 * All hardware pins, network settings, and task tuning in one place.
 * ═══════════════════════════════════════════════════════════════════════════ */

/* ─── WiFi ──────────────────────────────────────────────────────────────── */
#define WIFI_SSID               "Ge cafe"
    /* WiFi network name (SSID) — router/hotspot name to connect to */
#define WIFI_PASSWORD           "gexincamon"
    /* WiFi password — authentication for WPA2-PSK security */
#define WIFI_MAX_RETRY          5
    /* Max reconnection attempts if WiFi drops — after 5 fails, stop and wait for manual reset */

/* ─── TCP server (runs object detection, returns servo angles) ───────────── */
#define TCP_SERVER_IP           "192.168.1.77"
    /* Server IP running Python detection script — ESP connects here to send JPEG + receive servo angles */
    /* STATIC IP recommended (not DHCP) for reliability — if server IP changes, update this */
#define TCP_PORT_IMAGE          9000
    /* Port for sending JPEG frames (ESP→Server) — one-way stream (9000) */
    /* Separate port avoids TCP flow control blocking — sends while receiving independently */
#define TCP_PORT_CMD            9001
    /* Port for receiving servo commands (Server→ESP) — one-way stream (9001) */
    /* Lower priority than image streaming — can wait 3s for servo data */
#define TCP_CONNECT_TIMEOUT_MS  5000
    /* Timeout for TCP connect attempt (5 seconds) — if no response after 5s, retry */
    /* Too short: fails on slow networks; too long: WiFi jitter causes long hang */
#define TCP_RECV_TIMEOUT_MS     3000
    /* Timeout waiting for servo command data (3 seconds) — SO_RCVTIMEO socket option */
    /* If server doesn't send angles for 3s, recv returns error and task retries connect */

/* ─── Camera pins (OV5640 DVP) ───────────────────────────────────────────── */
    /* OV5640 uses DVP (Digital Video Port) — parallel 8-bit data bus + control signals */
    /* All pins must match your hardware wiring — verify PCB schematic before flashing */
#define CAM_PIN_PWDN            38
    /* Power down pin (active LOW) — deassert PWDN=HIGH to enable camera */
    /* If held LOW, OV5640 disables to save power; must release for operation */
#define CAM_PIN_RESET           47
    /* Reset pin (active LOW) — camera reset pulse; esp_camera_init() handles automatically */
    /* Resets sensor registers to defaults on startup */
#define CAM_PIN_XCLK            15
    /* Master clock output to OV5640 (20MHz) — generated by ESP32 LEDC_TIMER_0 */
    /* OV5640 uses this clock to synchronize internal pixel data generation */
#define CAM_PIN_SIOD            4
    /* I2C SDA (SCCB data) — serial control bus to configure OV5640 registers */
    /* SCCB is I2C-compatible protocol used by Omnivision sensors */
#define CAM_PIN_SIOC            5
    /* I2C SCL (SCCB clock) — serial control bus clock for register access */
#define CAM_PIN_D0              11
    /* DVP data bit 0 (LSB) — parallel data line from OV5640 sensor */
    /* 8 parallel bits (D0-D7) deliver raw pixel data simultaneously */
#define CAM_PIN_D1              9
    /* DVP data bit 1 */
#define CAM_PIN_D2              8
    /* DVP data bit 2 */
#define CAM_PIN_D3              10
    /* DVP data bit 3 */
#define CAM_PIN_D4              12
    /* DVP data bit 4 (middle) */
#define CAM_PIN_D5              18
    /* DVP data bit 5 */
#define CAM_PIN_D6              17
    /* DVP data bit 6 */
#define CAM_PIN_D7              16
    /* DVP data bit 7 (MSB) — most significant bit of 8-bit parallel data */
#define CAM_PIN_VSYNC           6
    /* Vertical sync — signals start of new video frame (1 pulse per frame) */
    /* Camera pulls LOW → HIGH for ~1 line to mark frame boundary */
#define CAM_PIN_HREF            7
    /* Horizontal reference — active during valid data period (one pulse per scanline) */
    /* LOW = data valid, HIGH = blanking period; tells ESP when to grab D0-D7 */
#define CAM_PIN_PCLK            13
    /* Pixel clock — rising edge clocks next byte into D0-D7 */
    /* DMA hardware samples D0-D7 on PCLK rising edges */

/* ─── Camera capture settings ────────────────────────────────────────────── */
#define CAM_XCLK_FREQ_HZ        20000000
    /* Master clock frequency 20MHz — OV5640 spec range 6-24MHz */
    /* Higher freq = faster pixel output; 20MHz balances speed + stability */
    /* LEDC_TIMER_0 generates this clock and drives pin 15 */
#define CAM_FRAME_SIZE          FRAMESIZE_VGA
    /* Output resolution: VGA = 640×480 pixels (BEST for AI detection) */
    /* VGA + quality 20 = ~90KB JPEG = 30fps + OPTIMAL for object detection */
    /* QVGA (320×240) TOO SMALL: AI can't recognize objects (too few pixels) */
    /* SVGA (800×600) if need more detail but FPS drops to 25-28 */
    /* UXGA (1600×1200) if need max quality but FPS drops to 12-15 (too slow) */
#define CAM_JPEG_QUALITY        15
    /* JPEG compression quality: 15 = ~60KB/frame (reduced from 20=~90KB) */
    /* 20fps × 60KB = 1.2MB/s → WiFi 54Mbps easily handles without queue backup */
    /* Quality 15 still good for VGA detection, artifacts barely noticeable */
#define CAM_FB_COUNT            6
    /* Number of frame buffers in PSRAM: 4 × ~90KB = 360KB total */
    /* 4 buffers optimal for ring buffer (enough for WiFi jitter) */
    /* More buffers (5+): Overkill, wastes PSRAM (8MB has plenty anyway) */
    /* Fewer buffers (2-3): May drop frames if WiFi congested */

/* ─── Servo pins (6-DOF robot arm, adjust to your wiring) ───────────────── */
    /* Each servo gets PWM signal from ESP32 LEDC — 50Hz signal with pulse width 500-2500µs */
    /* Pulse mapping: 500µs→0°, 2500µs→180°, 1500µs→90° (neutral) */
#define SERVO_PIN_0             1
    /* Base rotation servo — GPIO1 produces PWM for horizontal rotation */
#define SERVO_PIN_1             2
    /* Shoulder servo — GPIO2 lifts/lowers upper arm */
#define SERVO_PIN_2             42
    /* Elbow servo — GPIO42 bends forearm */
#define SERVO_PIN_3             41
    /* Wrist pitch servo — GPIO41 tilts wrist up/down */
#define SERVO_PIN_4             40
    /* Wrist roll servo — GPIO40 rotates wrist */
#define SERVO_PIN_5             39
    /* Gripper servo — GPIO39 opens/closes gripper claw */
#define SERVO_COUNT             6
    /* Total number of servos in array — must match number of pins */

/* ─── Servo PWM (LEDC) ───────────────────────────────────────────────────── */
    /* LEDC = LED PWM controller; used here for servo PWM generation */
    /* ESP32 has 16 LEDC channels; we use 6 channels for 6 servos */
#define SERVO_LEDC_FREQ_HZ      50
    /* Servo PWM frequency 50Hz (20ms period) — standard for hobby servos */
    /* Deviation: 48-52Hz OK, but <40Hz or >60Hz causes servo jitter/noise */
#define SERVO_LEDC_RESOLUTION   LEDC_TIMER_14_BIT
    /* Timer resolution 14-bit = 16384 steps per 20ms period */
    /* Step size = 20000µs / 16384 = 1.22µs precision */
    /* Sufficient for 500-2500µs range (requires ~1640 to ~20410 steps) */
#define SERVO_PULSE_MIN_US      500
    /* Pulse width for 0° position — 500µs at 50Hz = 2.5% duty cycle */
    /* Servo calibrated: pulse <500µs = beyond 0°; pulse >2500µs = beyond 180° */
#define SERVO_PULSE_MAX_US      2500
    /* Pulse width for 180° position — 2500µs at 50Hz = 12.5% duty cycle */
    /* Safe range avoids stalling servo past mechanical limits */
#define SERVO_ANGLE_MIN         0.0f
    /* Minimum commanded angle 0° — prevents negative commands */
#define SERVO_ANGLE_MAX         180.0f
    /* Maximum commanded angle 180° — prevents >180° commands */

/* ─── Task configuration ─────────────────────────────────────────────────── */
    /* FreeRTOS multi-task design: 4 tasks pinned to 2 cores */
    /* Core 0 (PRO_CPU): WiFi/TCP stack (WiFi interrupt handler runs here) */
    /* Core 1 (APP_CPU): Camera + Servo (isolated from WiFi latency) */
#define TASK_CORE_CAMERA        1
    /* camera_task pinned to Core 1 — DVP DMA and frame processing */
    /* Core 1 isolated from WiFi = smooth 8fps capture (no WiFi hiccups) */
#define TASK_CORE_TCP_SEND      0
    /* tcp_send_task pinned to Core 0 — sends JPEG frames via port 9000 */
    /* Core 0 has lwIP stack access (WiFi/TCP); better TCP throughput */
#define TASK_CORE_TCP_RECV      0
    /* tcp_recv_task pinned to Core 0 — listens for servo commands via port 9001 */
    /* Core 0 shares with WiFi stack (same core, different priority) */
#define TASK_CORE_SERVO         1
    /* servo_task pinned to Core 1 — PWM control for robot arm */
    /* Core 1 isolated = precise PWM timing, not interrupted by WiFi */

#define TASK_PRIO_CAMERA        5
    /* camera_task priority: HIGHER than tcp_send (5 > 4) */
    /* If both ready, camera runs first → captures fresh frames before WiFi delays */
    /* Prevents frame starvation when network busy */
#define TASK_PRIO_TCP_SEND      4
    /* tcp_send_task priority: medium — streaming frames is secondary to camera capture */
#define TASK_PRIO_TCP_RECV      4
    /* tcp_recv_task priority: same as send (4) — both depend on network, race condition OK */
#define TASK_PRIO_SERVO         6
    /* servo_task priority: HIGHEST (6 > all others) — PWM timing is critical */
    /* Servo commands must execute promptly (preempts all other Core 1 tasks) */

#define TASK_STACK_CAMERA       4096
    /* camera_task stack: 4KB — local variables + esp_camera_drv function calls */
    /* 4KB sufficient (no large buffers; pointer-only frame passing) */
#define TASK_STACK_TCP_SEND     8192
    /* tcp_send_task stack: 8KB — largest stack */
    /* Reason: socket operations (send_all loop), PSRAM frame pointer manipulation */
    /* Extra margin for TCP stack internal buffers */
#define TASK_STACK_TCP_RECV     4096
    /* tcp_recv_task stack: 4KB — receives 24-byte servo command, minimal processing */
#define TASK_STACK_SERVO        2048
    /* servo_task stack: 2KB — smallest; just updates servo angles via servo_ctrl.c */

/* ─── Queue depths ───────────────────────────────────────────────────────── */
    /* FreeRTOS queues pass frame pointers between tasks */
    /* Camera fills queue → TCP empties queue (producer-consumer pattern) */
#define FRAME_QUEUE_DEPTH       2
    /* Frame queue capacity: 2 pointers — ring buffer keeps 2 NEWEST frames */
    /* MUST satisfy: CAM_FB_COUNT(4) ≥ FRAME_QUEUE_DEPTH(2) + 2 → 4≥4 ✅ */
    /* depth=4 caused DMA stall: all 4 buffers locked in queue, camera blocked */
    /* depth=2 = enough for WiFi jitter absorption, no DMA starvation */
    /* Frame queue capacity: 4 pointers (not 4 copies of huge JPEG!) */
    /* Ring buffer: if camera_task full, evict oldest frame, push newest */
    /* Keeps MOST RECENT frames for stream (sacrifices old frames if WiFi slow) */
    /* SVGA JPEG ~25KB × 4 = 100KB PSRAM for queue storage */
#define CMD_QUEUE_DEPTH         1
    /* Servo command queue: depth MUST be 1 for xQueueOverwrite() function */
    /* xQueueOverwrite: always replaces single slot with latest servo angles */
    /* Prevents stale commands; only newest command from server matters */
